// <auto-generated />
using System;
using CarExpertise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarExpertise.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240707194956_CustomerControllerUpdated")]
    partial class CustomerControllerUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarExpertise.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CarExpertise.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AracKm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracMarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracMarkaId")
                        .HasColumnType("int");

                    b.Property<string>("AracModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracPlaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EkspertizId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ucret")
                        .HasColumnType("int");

                    b.Property<string>("YakitTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YedekAnahtar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarModelTable");
                });

            modelBuilder.Entity("CarExpertise.Models.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracMarkaId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MusteriAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTable");
                });

            modelBuilder.Entity("CarExpertise.Models.ExpertiseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ABS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ABSFren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Airbag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AksKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AkuDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amortisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracAltıMuhafaza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("AracKm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracMarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracMarkaId")
                        .HasColumnType("int");

                    b.Property<string>("AracModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracPlaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArkaPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArkaPodye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArkaTampon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aynalar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Camlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContaYanik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Davlumbaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difransiyel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DingilKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DipNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireksiyonPompa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosemeler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EgsozSitem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElektirikliDireksiyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnjektorDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Farlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenBalatalari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenDiskleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenHidrolik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gosterge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasarKmNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HavaFiltreKabinDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HavuzSaci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helezonlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HizSabitleyici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Jantlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kaput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlimaElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Korna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastikBasınçElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastikler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorArızaLambası")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorBeyinElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorFabrika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorGenel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorOlculen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorYag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnPodye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnTampon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkSensorleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Radyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotKollari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagArkaCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagArkaKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagArkaSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagMaspiyelArka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagMaspiyelOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOrtaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalincakBurc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanzumanDebriyaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SağArkaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Silecekler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolMaspiyelArka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolMaspiyelOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOrtaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stepne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sunroof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tavan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurboDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurboIntercoller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ucret")
                        .HasColumnType("int");

                    b.Property<string>("VKayis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YagSizdirmazlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitSistem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitSizdirmazlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakıtHortumlari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YedekAnahtar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_AksKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Amartisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_AracAltıMuhafaza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Aynalar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Camlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Davlumbaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Difransiyel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_DingilKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Farlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_FrenBalatalari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_FrenDiskleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Helezonlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Jantlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Klima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Lastikler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_RotKollari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_SalincakBurc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Silecekler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Stepne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_Sunroof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_YakıtHortumlari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_abs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_abs_fren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_airbag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_dosemeler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_elektrikli_direksiyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_esp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_esr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_gosterge_panelleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_hiz_sabitleyici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_klima_elektronigi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_korna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_lastik_basinc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_motor_ariza_lambasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_motor_beyin_elektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_park_sensorleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_radyo_teyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("not_sanziman_elektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_AkuDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_ArkaPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_ArkaPodye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_ArkaTampon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_Bagaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_ContaYanik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_DireksiyonPompa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_EgsozSitem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_EnjektorDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_FrenHidrolik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_HavaFiltreKabinDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_HavuzSaci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_Kaput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_MotorGenel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_MotorYag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_OnPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_OnPodye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_OnTampon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagArkaCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagArkaKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagArkaSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagMaspiyelArka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagMaspiyelOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagOnCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagOnDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagOnKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagOnSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SagOrtaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SanzumanDebriyaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SağArkaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolArkaCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolArkaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolArkaKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolArkaSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolMaspiyelArka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolMaspiyelOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolOnCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolOnDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolOnKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolOnSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_SolOrtaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_Tavan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_TurboDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_TurboIntercoller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_VKayis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_YagSizdirmazlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_YakitSistem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntsi_YakitSizdirmazlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ŞanzımanElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExpertiseTable");
                });

            modelBuilder.Entity("CarExpertise.Models.ExpertiseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ABS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ABSFren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Airbag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AksKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AkuDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amortisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracAltıMuhafaza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracKaporta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracMotor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArkaPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArkaPodye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArkaTampon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aynalar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bagaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Camlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContaYanik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Davlumbaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difransiyel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DingilKontrol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DipNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireksiyonPompa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosemeler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EgsozSitem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElektirikliDireksiyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElektronikSistem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnjektorDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Farlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenBalatalari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenDiskleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenHidrolik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gosterge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasarKmNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HavaFiltreKabinDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HavuzSaci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helezonlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HizSabitleyici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcDisAksesuar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Jantlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kaput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlimaElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Korna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastikBasınçElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastikler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorArızaLambası")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorBeyinElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorFabrika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorGenel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorOlculen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorPerformans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotorYag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnPodye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnTampon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkSensorleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Radyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotKollari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SablonAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagArkaCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagArkaKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagArkaSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagMaspiyelArka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagMaspiyelOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOnSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SagOrtaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalincakBurc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanzumanDebriyaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SağArkaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Silecekler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolArkaSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolMaspiyelArka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolMaspiyelOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnCamurluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnKapi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOnSase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolOrtaDirek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stepne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sunroof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tavan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurboDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurboIntercoller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VKayis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YagSizdirmazlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitSistem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitSizdirmazlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakıtHortumlari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YuruyenAksam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("updateId")
                        .HasColumnType("int");

                    b.Property<string>("ŞanzımanElektroniği")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExpertiseTemplateTable");
                });

            modelBuilder.Entity("CarExpertise.Models.TryVehicle", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("AracKm")
                        .HasColumnType("int");

                    b.Property<string>("AracMarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracMarkaId")
                        .HasColumnType("int");

                    b.Property<string>("AracModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracPlaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ucret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YedekAnahtar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trys");
                });

            modelBuilder.Entity("CarExpertise.Models.VehicleModels", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("AracKm")
                        .HasColumnType("int");

                    b.Property<string>("AracMarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AracMarkaId")
                        .HasColumnType("int");

                    b.Property<string>("AracModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracPlaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MusteriAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ucret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YedekAnahtar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VehicleModelss");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarExpertise.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarExpertise.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarExpertise.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarExpertise.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
